# Generated by Django 5.2.6 on 2025-10-01 15:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("links", "0001_initial"),
        ("links", "0002_platform_alter_link_platform"),
        ("links", "0003_platform_platform_regex"),
        ("links", "0004_alter_platform_platform_name"),
        ("links", "0005_remove_platform_platform_regex_platform_domain_and_more"),
        ("links", "0006_remove_platform_domain_remove_platform_scheme_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform_name", models.CharField(max_length=255)),
                (
                    "platform_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hex_color",
                                message="Enter a valid hex color like #RRGGBB.",
                                regex="^#(?:[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "platform_icon",
                    models.FileField(
                        upload_to="platform-svgs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg"],
                                message="File must be an .svg.",
                            )
                        ],
                    ),
                ),
                (
                    "platform_origin",
                    models.CharField(
                        default="",
                        help_text="Origin for platform (ie https://www.github.com)",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_platform_origin",
                                message="Please enter a valid origin",
                                regex="^(https?):\\/\\/(www\\.)?[A-Za-z0-9.-]+(?::\\d+)?$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="links.platform"
                    ),
                ),
                ("link_url", models.URLField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
