# Generated by Django 5.2.6 on 2025-10-01 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "links",
            "0001_squashed_0006_remove_platform_domain_remove_platform_scheme_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="platform_origin",
            field=models.CharField(
                help_text="Origin for platform (ie https://www.github.com)",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_platform_origin",
                        message="Please enter a valid origin",
                        regex="^(https?):\\/\\/(www\\.)?[A-Za-z0-9.-]+(?::\\d+)?$",
                    )
                ],
            ),
        ),
    ]
