# Generated by Django 5.2.6 on 2025-10-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0007_alter_platform_platform_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
