# Generated by Django 5.2.6 on 2025-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_profile_image_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_test_user",
            field=models.BooleanField(default=False),
        ),
    ]
