# Generated by Django 5.2.6 on 2025-10-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_test_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_test_user",
        ),
    ]
