# Generated by Django 5.2.6 on 2025-10-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_is_test_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_test_user",
            field=models.BooleanField(default=False),
        ),
    ]
